part of 'theme.dart';

/// Generated by Forui CLI.
///
/// Icon tokens for the generated theme.
FIcons _icons() => FIcons(
  arrowLeft: const FIcon(FPhosphorIcons.arrowLeft),
  calendar: const FIcon(FPhosphorIcons.calendarBlank),
  check: const FIcon(FPhosphorIcons.check),
  chevronDown: const FIcon(FPhosphorIcons.caretDown),
  chevronLeft: const FIcon(FPhosphorIcons.caretLeft),
  chevronRight: const FIcon(FPhosphorIcons.caretRight),
  chevronUp: const FIcon(FPhosphorIcons.caretUp),
  chevronsUpDown: const FIcon(FPhosphorIcons.caretUpDown),
  circleAlert: const FIcon(FPhosphorIcons.warningCircle),
  clock4: const FIcon(FPhosphorIcons.clock),
  ellipsis: const FIcon(FPhosphorIcons.dotsThree),
  error: const FIcon(FPhosphorIcons.warningCircle),
  eye: const FIcon(FPhosphorIcons.eye),
  eyeClosed: const FIcon(FPhosphorIcons.eyeClosed),
  gripHorizontal: const FIcon(FPhosphorIcons.dotsSix),
  gripVertical: const FIcon(FPhosphorIcons.dotsSixVertical),
  loader: const FIcon(FPhosphorIcons.spinner),
  loaderCircle: const FIcon(FPhosphorIcons.circleNotch),
  loaderPinwheel: const FIcon(FPhosphorIcons.spinnerBall),
  search: const FIcon(FPhosphorIcons.magnifyingGlass),
  userRound: const FIcon(FPhosphorIcons.userCircle),
  x: const FIcon(FPhosphorIcons.x),
);
