import 'package:cupertino_ui/cupertino_ui.dart';
import 'package:material_ui/material_ui.dart';

import 'package:forui/forui.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FTheme.neutral.light.touch.color,
///  style: FTheme.neutral.light.touch.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FTheme.neutral.light.touch.color,
///    style: FTheme.neutral.light.touch.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/guides/customizing-themes for more information.
FButtonStyles buttonStyles({
  required FColors colors,
  required FTypography typography,
  required FStyle style,
  required bool touch,
}) {
  final primary = _buttonSizeStyles(
    typography: typography,
    style: style,
    touch: touch,
    decoration: (radius) => .from(
      ShapeDecoration(
        shape: RoundedSuperellipseBorder(borderRadius: radius),
        color: colors.primary,
      ),
      variants: {
        [.hovered, .focused, .pressed]: .shapeDelta(color: colors.hover(colors.primary)),
        [.disabled]: .shapeDelta(color: colors.disable(colors.primary)),
        [.selected]: .shapeDelta(color: colors.hover(colors.primary)),
        [.selected.and(.disabled)]: .shapeDelta(
          color: colors.disable(colors.hover(colors.primary)),
        ),
      },
    ),
    foregroundColor: colors.primaryForeground,
    disabledForegroundColor: colors.disable(colors.primaryForeground),
  );
  return FButtonStyles(
    FVariants(
      primary,
      variants: {
        [.primary]: primary,
        [.secondary]: .inherit(
          typography: typography,
          style: style,
          touch: touch,
          decoration: (radius) => .from(
            ShapeDecoration(
              shape: RoundedSuperellipseBorder(borderRadius: radius),
              color: colors.secondary,
            ),
            variants: {
              [.hovered, .focused, .pressed]: .shapeDelta(
                color: colors.hover(colors.secondary),
              ),
              [.disabled]: .shapeDelta(color: colors.disable(colors.secondary)),
              [.selected]: .shapeDelta(color: colors.hover(colors.secondary)),
              [.selected.and(.disabled)]: .shapeDelta(
                color: colors.disable(colors.hover(colors.secondary)),
              ),
            },
          ),
          foregroundColor: colors.secondaryForeground,
          disabledForegroundColor: colors.disable(colors.secondaryForeground),
        ),
        [.destructive]: .inherit(
          typography: typography,
          style: style,
          touch: touch,
          decoration: (radius) => .from(
            ShapeDecoration(
              shape: RoundedSuperellipseBorder(borderRadius: radius),
              color: colors.destructive.withValues(
                alpha: colors.brightness == .light ? 0.1 : 0.2,
              ),
            ),
            variants: {
              [.hovered, .focused, .pressed]: .shapeDelta(
                color: colors.destructive.withValues(
                  alpha: colors.brightness == .light ? 0.2 : 0.3,
                ),
              ),
              [.disabled]: .shapeDelta(
                color: colors.destructive.withValues(
                  alpha: colors.brightness == .light ? 0.05 : 0.1,
                ),
              ),
              [.selected]: .shapeDelta(
                color: colors.destructive.withValues(
                  alpha: colors.brightness == .light ? 0.2 : 0.3,
                ),
              ),
              [.selected.and(.disabled)]: .shapeDelta(
                color: colors.disable(
                  colors.destructive.withValues(
                    alpha: colors.brightness == .light ? 0.2 : 0.3,
                  ),
                ),
              ),
            },
          ),
          foregroundColor: colors.destructive,
          disabledForegroundColor: colors.destructive.withValues(alpha: 0.5),
        ),
        [.outline]: .inherit(
          typography: typography,
          style: style,
          touch: touch,
          decoration: (radius) => .from(
            ShapeDecoration(
              shape: RoundedSuperellipseBorder(
                side: BorderSide(
                  color: colors.border,
                  width: style.borderWidth,
                ),
                borderRadius: radius,
              ),
              color: colors.card,
            ),
            variants: {
              [.hovered, .focused, .pressed]: .shapeDelta(color: colors.secondary),
              [.disabled]: .shapeDelta(color: colors.disable(colors.card)),
              [.selected]: .shapeDelta(color: colors.secondary),
              [.selected.and(.disabled)]: .shapeDelta(
                color: colors.disable(colors.secondary),
              ),
            },
          ),
          foregroundColor: colors.secondaryForeground,
          disabledForegroundColor: colors.disable(colors.secondaryForeground),
        ),
        [.ghost]: .inherit(
          typography: typography,
          style: style,
          touch: touch,
          decoration: (radius) => .from(
            ShapeDecoration(
              shape: RoundedSuperellipseBorder(borderRadius: radius),
            ),
            variants: {
              [.hovered, .focused, .pressed]: .shapeDelta(color: colors.secondary),
              [.disabled]: const .shapeDelta(),
              [.selected]: .shapeDelta(color: colors.secondary),
              [.selected.and(.disabled)]: .shapeDelta(
                color: colors.disable(colors.secondary),
              ),
            },
          ),
          foregroundColor: colors.secondaryForeground,
          disabledForegroundColor: colors.disable(colors.secondaryForeground),
        ),
      },
    ),
  );
}

FButtonSizeStyles _buttonSizeStyles({
  required FTypography typography,
  required FStyle style,
  required FVariants<
      FTappableVariantConstraint,
      FTappableVariant,
      Decoration,
      DecorationDelta
  >
  Function(BorderRadiusGeometry radius)
  decoration,
  required Color foregroundColor,
  required Color disabledForegroundColor,
  required bool touch,
}) {
  if (touch) {
    final md = _buttonStyle(
      style: style,
      foregroundColor: foregroundColor,
      disabledForegroundColor: disabledForegroundColor,
      decoration: decoration(style.borderRadius.md),
      textStyle: typography.body.sm,
      contentConstraints: const BoxConstraints(minWidth: 44, minHeight: 44),
      contentPadding: const .symmetric(horizontal: 12, vertical: 14),
      contentSpacing: 6,
      iconConstraints: const BoxConstraints(minWidth: 44, minHeight: 44),
      iconSize: typography.body.md.fontSize ?? 18,
      iconPadding: const .all(13),
    );
    return FButtonSizeStyles(
      FVariants(
        md,
        variants: {
          [.xs]: _buttonStyle(
            style: style,
            foregroundColor: foregroundColor,
            disabledForegroundColor: disabledForegroundColor,
            decoration: decoration(style.borderRadius.sm),
            textStyle: typography.body.xs,
            contentConstraints: const BoxConstraints(
              minWidth: 32,
              minHeight: 32,
            ),
            contentPadding: const .symmetric(horizontal: 10, vertical: 9),
            contentSpacing: 4,
            iconConstraints: const BoxConstraints(minWidth: 32, minHeight: 32),
            iconSize: typography.body.sm.fontSize ?? 16,
            iconPadding: const .all(8),
          ),
          [.sm]: _buttonStyle(
            style: style,
            foregroundColor: foregroundColor,
            disabledForegroundColor: disabledForegroundColor,
            decoration: decoration(style.borderRadius.md),
            textStyle: typography.body.sm,
            contentConstraints: const BoxConstraints(
              minWidth: 40,
              minHeight: 40,
            ),
            contentPadding: const .symmetric(horizontal: 12, vertical: 12),
            contentSpacing: 4,
            iconConstraints: const BoxConstraints(minWidth: 40, minHeight: 40),
            iconSize: typography.body.md.fontSize ?? 18,
            iconPadding: const .all(11),
          ),
          [.md]: md,
          [.lg]: _buttonStyle(
            style: style,
            foregroundColor: foregroundColor,
            disabledForegroundColor: disabledForegroundColor,
            decoration: decoration(style.borderRadius.md),
            textStyle: typography.body.sm,
            contentConstraints: const BoxConstraints(
              minWidth: 48,
              minHeight: 48,
            ),
            contentPadding: const .symmetric(horizontal: 12, vertical: 16),
            contentSpacing: 6,
            iconConstraints: const BoxConstraints(minWidth: 48, minHeight: 48),
            iconSize: typography.body.lg.fontSize ?? 20,
            iconPadding: const .all(14),
          ),
        },
      ),
    );
  } else {
    final md = _buttonStyle(
      style: style,
      foregroundColor: foregroundColor,
      disabledForegroundColor: disabledForegroundColor,
      decoration: decoration(style.borderRadius.md),
      textStyle: typography.body.sm,
      contentConstraints: const BoxConstraints(minWidth: 36, minHeight: 36),
      contentPadding: const .symmetric(horizontal: 10, vertical: 11),
      contentSpacing: 6,
      iconConstraints: const BoxConstraints(minWidth: 36, minHeight: 36),
      iconSize: typography.body.md.fontSize ?? 16,
      iconPadding: const .all(10),
    );
    return FButtonSizeStyles(
      FVariants(
        md,
        variants: {
          [.xs]: _buttonStyle(
            style: style,
            foregroundColor: foregroundColor,
            disabledForegroundColor: disabledForegroundColor,
            decoration: decoration(style.borderRadius.sm),
            textStyle: typography.body.xs,
            contentConstraints: const BoxConstraints(
              minWidth: 24,
              minHeight: 24,
            ),
            contentPadding: const .symmetric(horizontal: 8, vertical: 6),
            contentSpacing: 4,
            iconConstraints: const BoxConstraints(minWidth: 24, minHeight: 24),
            iconSize: typography.body.sm.fontSize ?? 14,
            iconPadding: const .all(5),
          ),
          [.sm]: _buttonStyle(
            style: style,
            foregroundColor: foregroundColor,
            disabledForegroundColor: disabledForegroundColor,
            decoration: decoration(style.borderRadius.md),
            textStyle: typography.body.sm,
            contentConstraints: const BoxConstraints(
              minWidth: 32,
              minHeight: 32,
            ),
            contentPadding: const .symmetric(horizontal: 10, vertical: 9),
            contentSpacing: 4,
            iconConstraints: const BoxConstraints(minWidth: 32, minHeight: 32),
            iconSize: typography.body.md.fontSize ?? 16,
            iconPadding: const .all(8),
          ),
          [.md]: md,
          [.lg]: _buttonStyle(
            style: style,
            foregroundColor: foregroundColor,
            disabledForegroundColor: disabledForegroundColor,
            decoration: decoration(style.borderRadius.md),
            textStyle: typography.body.sm,
            contentConstraints: const BoxConstraints(
              minWidth: 40,
              minHeight: 40,
            ),
            contentPadding: const .symmetric(horizontal: 10, vertical: 13),
            contentSpacing: 6,
            iconConstraints: const BoxConstraints(minWidth: 40, minHeight: 40),
            iconSize: typography.body.lg.fontSize ?? 18,
            iconPadding: const .all(11),
          ),
        },
      ),
    );
  }
}

FButtonStyle _buttonStyle({
  required FStyle style,
  required FVariants<
      FTappableVariantConstraint,
      FTappableVariant,
      Decoration,
      DecorationDelta
  >
  decoration,
  required Color foregroundColor,
  required Color disabledForegroundColor,
  required TextStyle textStyle,
  required BoxConstraints contentConstraints,
  required EdgeInsetsGeometry contentPadding,
  required double contentSpacing,
  required BoxConstraints iconConstraints,
  required double iconSize,
  required EdgeInsetsGeometry iconPadding,
}) => FButtonStyle(
  decoration: decoration,
  // No ring around a focused button: it fills in like on hover instead (the .focused entries above).
  focusedOutlineStyle: style.focusedOutlineStyle.copyWith(color: const Color(0x00000000)),
  contentStyle: FButtonContentStyle(
    textStyle: .from(
      textStyle.copyWith(color: foregroundColor, fontWeight: .w500, height: 1),
      variants: {
        [.disabled]: .delta(color: disabledForegroundColor),
      },
    ),
    iconStyle: .from(
      IconThemeData(color: foregroundColor, size: textStyle.fontSize),
      variants: {
        [.disabled]: .delta(color: disabledForegroundColor),
      },
    ),
    circularProgressStyle: .from(
      FCircularProgressStyle(
        iconStyle: IconThemeData(
          color: foregroundColor,
          size: textStyle.fontSize,
        ),
      ),
      variants: {
        [.disabled]: .delta(iconStyle: .delta(color: disabledForegroundColor)),
      },
    ),
    padding: contentPadding,
    spacing: contentSpacing,
    constraints: contentConstraints,
  ),
  iconContentStyle: FButtonIconContentStyle(
    iconStyle: .from(
      IconThemeData(color: foregroundColor, size: iconSize),
      variants: {
        [.disabled]: .delta(color: disabledForegroundColor),
      },
    ),
    padding: iconPadding,
    constraints: iconConstraints,
  ),
  tappableStyle: style.tappableStyle,
);