import 'package:cupertino_ui/cupertino_ui.dart';
import 'package:material_ui/material_ui.dart';

import 'package:forui/forui.dart';

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FTheme.neutral.light.touch.color,
///  style: FTheme.neutral.light.touch.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FTheme.neutral.light.touch.color,
///    style: FTheme.neutral.light.touch.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/guides/customizing-themes for more information.
FSidebarStyle sidebarStyle({
  required FColors colors,
  required FTypography typography,
  required FIcons icons,
  required FStyle style,
  required bool touch,
}) => FSidebarStyle(
  decoration: BoxDecoration(
    color: colors.background,
    border: .fromSTEB(
      end: BorderSide(color: colors.border, width: style.borderWidth),
    ),
  ),
  groupStyle: _sidebarGroupStyle(
    colors: colors,
    typography: typography,
    icons: icons,
    style: style,
    touch: touch,
  ),
  constraints: const .tightFor(width: 256),
  headerPadding: const .fromLTRB(0, 8, 0, 0),
  contentPadding: const .symmetric(vertical: 8),
  footerPadding: const .fromLTRB(0, 0, 0, 8),
);

/// The ring around whatever has focus, made invisible: in the sidebar, focus shows as the
/// same fill as hovering instead (see the `.focused` entries below).
FFocusedOutlineStyle _noRing(FStyle style) =>
    style.focusedOutlineStyle.copyWith(color: const Color(0x00000000));

FSidebarGroupStyle _sidebarGroupStyle({
  required FColors colors,
  required FTypography typography,
  required FIcons icons,
  required FStyle style,
  required bool touch,
}) => FSidebarGroupStyle(
  labelStyle: typography.body.xs.copyWith(
    color: colors.mutedForeground,
    overflow: .ellipsis,
    fontWeight: .w500,
  ),
  actionStyle: .from(
    IconThemeData(color: colors.mutedForeground, size: typography.body.md.fontSize),
    variants: {
      [.hovered, .focused, .pressed]: .delta(color: colors.foreground),
    },
  ),
  tappableStyle: style.tappableStyle,
  focusedOutlineStyle: _noRing(style),
  itemStyle: _sidebarItemStyle(
    colors: colors,
    typography: typography,
    icons: icons,
    style: style,
    touch: touch,
  ),
);

FSidebarItemStyle _sidebarItemStyle({
  required FColors colors,
  required FTypography typography,
  required FIcons icons,
  required FStyle style,
  required bool touch,
}) => FSidebarItemStyle(
  textStyle: .from(
    typography.body.sm.copyWith(color: colors.foreground, overflow: .ellipsis, height: 1),
    variants: {
      [.disabled]: .delta(color: colors.mutedForeground),
    },
  ),
  iconStyle: .from(
    IconThemeData(color: colors.foreground, size: 16),
    variants: {
      [.disabled]: .delta(color: colors.mutedForeground),
    },
  ),
  collapsibleIconStyle: .from(
    IconThemeData(color: colors.foreground, size: 16),
    variants: {
      [.disabled]: .delta(color: colors.mutedForeground),
    },
  ),
  collapsibleIcon: icons.chevronRight,
  backgroundColor: FVariants(
    colors.background,
    variants: {
      [.selected, .hovered, .focused, .pressed]: colors.secondary,
      //
      [.disabled]: colors.background,
    },
  ),
  padding: touch ? const .symmetric(horizontal: 12, vertical: 14) : const .all(8),
  borderRadius: style.borderRadius.md,
  tappableStyle: style.tappableStyle.copyWith(motion: FTappableMotion.none),
  focusedOutlineStyle: _noRing(style).copyWith(spacing: 0),
);